#pragma once

/*
	Gamepad button codes for Xaloc.
	Taken from glfw3.h key codes.
*/

#define XA_GAMEPAD_BUTTON_A               0
#define XA_GAMEPAD_BUTTON_B               1
#define XA_GAMEPAD_BUTTON_X               2
#define XA_GAMEPAD_BUTTON_Y               3
#define XA_GAMEPAD_BUTTON_LEFT_BUMPER     4
#define XA_GAMEPAD_BUTTON_RIGHT_BUMPER    5
#define XA_GAMEPAD_BUTTON_BACK            6
#define XA_GAMEPAD_BUTTON_START           7
#define XA_GAMEPAD_BUTTON_GUIDE           8
#define XA_GAMEPAD_BUTTON_LEFT_THUMB      9
#define XA_GAMEPAD_BUTTON_RIGHT_THUMB     10
#define XA_GAMEPAD_BUTTON_DPAD_UP         11
#define XA_GAMEPAD_BUTTON_DPAD_RIGHT      12
#define XA_GAMEPAD_BUTTON_DPAD_DOWN       13
#define XA_GAMEPAD_BUTTON_DPAD_LEFT       14
#define XA_GAMEPAD_BUTTON_LAST            XA_GAMEPAD_BUTTON_DPAD_LEFT

#define XA_GAMEPAD_BUTTON_CROSS       XA_GAMEPAD_BUTTON_A
#define XA_GAMEPAD_BUTTON_CIRCLE      XA_GAMEPAD_BUTTON_B
#define XA_GAMEPAD_BUTTON_SQUARE      XA_GAMEPAD_BUTTON_X
#define XA_GAMEPAD_BUTTON_TRIANGLE    XA_GAMEPAD_BUTTON_Y
